# Generated by Django 4.2.8 on 2023-12-25 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('about', models.TextField(blank=True, max_length=200)),
                ('profilePic', models.ImageField(default=None, upload_to='profilePic')),
                ('DOB', models.DateField()),
            ],
        ),
    ]
