# Generated by Django 4.2.8 on 2023-12-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weConnectApp', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='CreatePost',
        ),
    ]
