# Generated by Django 4.2.8 on 2023-12-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weConnectApp', '0004_rename_createpost_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
